# Deployment aplicação
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
        - name: dotnet
          image: carlossma/conversao-peso:runtime
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet
spec:
  selector:
    app: dotnet
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
